export type AnalystRanks = Record<string, number>;
export type AnalystTimestamps = Record<string, string>;

export interface FlockRankingsResponse {
  format: string;
  subformat: string;
  year: number;
  pickType: string;
  subscribed: boolean;
  specialTeamsRankingsYear: string;
  lastUpdated: AnalystTimestamps;
  data: FlockPlayerRanking[];
}

export interface FlockPlayerRanking {
  playerId: number;
  underdogId: string | null;
  playerName: string;

  position: string;
  team: string | null;
  teamColor: string | null;

  isDraftPick: boolean;
  pickType: string | null;
  draftPickParent: unknown | null;
  autoGenerated: boolean;

  age: number | null;
  dob: string | null;
  experience: number | null;
  draftYear: number | null;
  college: string | null;

  fantasyCalcId: number | null;

  height: string | null;
  weight: string | null;

  isRookie: boolean;
  isActive: boolean;

  jerseyNumber: number | null;

  picture: string | null;
  image: string | null;

  averageRank: number;
  overallAverageRank: number;

  overallRanks: AnalystRanks;
  overallTiers: AnalystRanks;
  positionalTiers: AnalystRanks;

  weeklyOverallRanks: Record<string, unknown>;

  previousYearPprAverage: string | null;

  averageTier: number;
  averagePositionalTier: number;

  positionalRanks: AnalystRanks;
  averagePositionalRank: number;

  byeWeek: number | null;

  injury: { concernLevel: string, expectedReturn: string, doctorNotes: string } | null;

  rankDelta: number;
  initialRank: number;
  finalRank: number;
}

export default defineEventHandler(
  async (event): Promise<FlockRankingsResponse> => {
    try {
      return await $fetch<FlockRankingsResponse>("/rankings", {
        baseURL: "https://api.flockfantasy.com",

        query: {
          format: "REDRAFT",
          pickType: "hybrid",
          year: 2025,
          deltaRankType: "overall",
          deltaFormat: "REDRAFT",
          deltaSubformat: "1QB",
          includeRankingsPageGroups: true,
        },

        timeout: 5_000,
        retry: 1,
      });
    } catch (error) {
      console.error("Failed to fetch Flock rankings:", error);

      throw createError({
        statusCode: 502,
        statusMessage: "Unable to fetch fantasy rankings",
      });
    }
  },
);
